In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv('Datasets/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.drop(['RowNumber','CustomerId','Surname'], axis= 'columns', inplace=True)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [5]:
def print_unique_col_values(df):
    for column in df:
        if df[column].dtypes == 'object':
            print(f'{column}: {df[column].unique()}')

In [6]:
print_unique_col_values(df)

Geography: ['France' 'Spain' 'Germany']
Gender: ['Female' 'Male']

In [7]:
df1 = pd.get_dummies(data=df, columns=['Geography', 'Gender'])
df1.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_France',
       'Geography_Germany', 'Geography_Spain', 'Gender_Female', 'Gender_Male'],
      dtype='object')

In [8]:
print_unique_col_values(df1)

In [9]:
df1.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [11]:
col_to_scale=['CreditScore', 'Age', 'Tenure','Balance', 'NumOfProducts', 'EstimatedSalary']

In [12]:
df1[col_to_scale] = scaler.fit_transform(df1[col_to_scale])

In [13]:
df1.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,0.538,0.324324,0.2,0.000000,0.000000,1,1,0.506735,1,1,0,0,1,0
1,0.516,0.310811,0.1,0.334031,0.000000,0,1,0.562709,0,0,0,1,1,0
2,0.304,0.324324,0.8,0.636357,0.666667,1,0,0.569654,1,1,0,0,1,0
3,0.698,0.283784,0.1,0.000000,0.333333,0,0,0.469120,0,1,0,0,1,0
4,1.000,0.337838,0.2,0.500246,0.000000,1,1,0.395400,0,0,0,1,1,0

In [14]:
X = df1.drop('Exited',axis='columns')
y = df1.Exited

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10, stratify=y)

In [16]:
X_train.shape

(8000, 13)

In [17]:
X_test.shape

(2000, 13)

In [18]:
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix, classification_report

In [19]:
def ANN(X_train, y_train, X_test, y_test, loss):
    model = keras.Sequential([
        keras.layers.Dense(13, input_dim=13, activation='relu'),
        keras.layers.Dense(10, activation='relu'),
        keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

    
    model.fit(X_train, y_train, epochs=100)

    print(model.evaluate(X_test, y_test))

    y_preds = model.predict(X_test)
    y_preds = np.round(y_preds)

    print("Classification Report: \n", classification_report(y_test, y_preds))

    return y_preds

In [20]:
y_preds = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5030 - accuracy: 0.7945
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4644 - accuracy: 0.7984
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4507 - accuracy: 0.8060
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4398 - accuracy: 0.8098
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4332 - accuracy: 0.8102
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4293 - accuracy: 0.8129
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4234 - accuracy: 0.8166
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8232
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4122 - accuracy: 0.8278
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4058 - accuracy: 0.8319
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3999 - accuracy: 0.8378
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3930 - accuracy: 0.8393
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3852 - accuracy: 0.8428
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3757 - accuracy: 0.8438
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3681 - accuracy: 0.8486
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3624 - accuracy: 0.8526
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3566 - accuracy: 0.8555
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3538 - accuracy: 0.8554
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3501 - accuracy: 0.8568
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3493 - accuracy: 0.8591
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3466 - accuracy: 0.8587
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3471 - accuracy: 0.8585
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3456 - accuracy: 0.8589
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3440 - accuracy: 0.8589
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3445 - accuracy: 0.8601
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3433 - accuracy: 0.8583
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3427 - accuracy: 0.8605
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3424 - accuracy: 0.8586
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3418 - accuracy: 0.8594
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3428 - accuracy: 0.8574
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.8600
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3412 - accuracy: 0.8616
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3414 - accuracy: 0.8608
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3405 - accuracy: 0.8594
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8601
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8586
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3395 - accuracy: 0.8615
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3396 - accuracy: 0.8600
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8625
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3403 - accuracy: 0.8600
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8601
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8589
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3377 - accuracy: 0.8616
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3377 - accuracy: 0.8606
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3367 - accuracy: 0.8612
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3370 - accuracy: 0.8625
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8631
Epoch 48/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3368 - accuracy: 0.8597
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3372 - accuracy: 0.8604
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3384 - accuracy: 0.8611
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8611
Epoch 52/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3361 - accuracy: 0.8608
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8605
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8608
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8608
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3361 - accuracy: 0.8600
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8609
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8610
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8602
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8627
Epoch 61/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3353 - accuracy: 0.8614
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8616
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3353 - accuracy: 0.8625
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8625
Epoch 65/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8630
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8626
Epoch 67/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8626
Epoch 68/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8615
Epoch 69/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8625
Epoch 70/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8634
Epoch 71/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8624
Epoch 72/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8624
Epoch 73/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8611
Epoch 74/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8626
Epoch 75/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8630
Epoch 76/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8650
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8624
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8634
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8636
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8612
Epoch 81/100

250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8627
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8641
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8634
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8639
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8629
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8626
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8616
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8643
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8645
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8643
Epoch 91/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8646
Epoch 92/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8641
Epoch 93/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8630
Epoch 94/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8631
Epoch 95/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8652
Epoch 96/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8654
Epoch 97/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8645
Epoch 98/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8645
Epoch 99/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8648
Epoch 100/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3311 - accuracy: 0.8612
63/63 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8665
[0.3323747217655182, 0.8665000200271606]
63/63 [==============================] - 0s 965us/step
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.96      0.92      1593
           1       0.77      0.49      0.60       407

    accuracy                           0.87      2000
   macro avg       0.83      0.73      0.76      2000
weighted avg       0.86      0.87      0.85      2000

### undersampling

In [21]:
# Class count
count_class_0, count_class_1 = df1.Exited.value_counts()

# Divide by class
df_class_0 = df1[df1['Exited'] == 0]
df_class_1 = df1[df1['Exited'] == 1]

In [22]:
df_class_0_under = df_class_0.sample(count_class_1)
df_test_under = pd.concat([df_class_0_under, df_class_1], axis=0)

print('Random under-sampling:')
print(df_test_under.Exited.value_counts())

Random under-sampling:
0    2037
1    2037
Name: Exited, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
X = df_test_under.drop('Exited', axis='columns')
y = df_test_under['Exited']

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=15, stratify=y)

In [24]:
y_train.value_counts()

1    1630
0    1629
Name: Exited, dtype: int64

In [25]:
y_preds = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

Epoch 1/100
102/102 [==============================] - 1s 1ms/step - loss: 0.6799 - accuracy: 0.5787
Epoch 2/100
102/102 [==============================] - 0s 2ms/step - loss: 0.6466 - accuracy: 0.6410
Epoch 3/100
102/102 [==============================] - 0s 2ms/step - loss: 0.6332 - accuracy: 0.6493
Epoch 4/100
102/102 [==============================] - 0s 2ms/step - loss: 0.6242 - accuracy: 0.6622
Epoch 5/100
102/102 [==============================] - 0s 1ms/step - loss: 0.6173 - accuracy: 0.6609
Epoch 6/100
102/102 [==============================] - 0s 2ms/step - loss: 0.6116 - accuracy: 0.6689
Epoch 7/100
102/102 [==============================] - 0s 2ms/step - loss: 0.6047 - accuracy: 0.6747
Epoch 8/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5986 - accuracy: 0.6806
Epoch 9/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5928 - accuracy: 0.6855
Epoch 10/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5855 - accuracy: 0.6938
Epoch 11/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5787 - accuracy: 0.7014
Epoch 12/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5720 - accuracy: 0.7073
Epoch 13/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5644 - accuracy: 0.7125
Epoch 14/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5582 - accuracy: 0.7165
Epoch 15/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5508 - accuracy: 0.7211
Epoch 16/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5438 - accuracy: 0.7321
Epoch 17/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5387 - accuracy: 0.7303
Epoch 18/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5309 - accuracy: 0.7404
Epoch 19/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5237 - accuracy: 0.7429
Epoch 20/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5185 - accuracy: 0.7444
Epoch 21/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5134 - accuracy: 0.7465
Epoch 22/100
102/102 [==============================] - 0s 1ms/step - loss: 0.5089 - accuracy: 0.7515
Epoch 23/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5036 - accuracy: 0.7542
Epoch 24/100
102/102 [==============================] - 0s 2ms/step - loss: 0.5009 - accuracy: 0.7536
Epoch 25/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4982 - accuracy: 0.7564
Epoch 26/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4955 - accuracy: 0.7545
Epoch 27/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4926 - accuracy: 0.7530
Epoch 28/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4911 - accuracy: 0.7551
Epoch 29/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4906 - accuracy: 0.7576
Epoch 30/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4883 - accuracy: 0.7561
Epoch 31/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4871 - accuracy: 0.7588
Epoch 32/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4856 - accuracy: 0.7585
Epoch 33/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4852 - accuracy: 0.7616
Epoch 34/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4827 - accuracy: 0.7588
Epoch 35/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4816 - accuracy: 0.7591
Epoch 36/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4812 - accuracy: 0.7637
Epoch 37/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4805 - accuracy: 0.7634
Epoch 38/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4782 - accuracy: 0.7622
Epoch 39/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4802 - accuracy: 0.7591
Epoch 40/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4772 - accuracy: 0.7607
Epoch 41/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4751 - accuracy: 0.7631
Epoch 42/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4758 - accuracy: 0.7588
Epoch 43/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4735 - accuracy: 0.7665
Epoch 44/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4736 - accuracy: 0.7686
Epoch 45/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4739 - accuracy: 0.7656
Epoch 46/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4745 - accuracy: 0.7637
Epoch 47/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4711 - accuracy: 0.7671
Epoch 48/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4723 - accuracy: 0.7643
Epoch 49/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4699 - accuracy: 0.7616
Epoch 50/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4683 - accuracy: 0.7674
Epoch 51/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4701 - accuracy: 0.7686
Epoch 52/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4689 - accuracy: 0.7640
Epoch 53/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4686 - accuracy: 0.7680
Epoch 54/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4657 - accuracy: 0.7680
Epoch 55/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4659 - accuracy: 0.7714
Epoch 56/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4657 - accuracy: 0.7680
Epoch 57/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4665 - accuracy: 0.7662
Epoch 58/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4655 - accuracy: 0.7726
Epoch 59/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4636 - accuracy: 0.7705
Epoch 60/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4632 - accuracy: 0.7668
Epoch 61/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4637 - accuracy: 0.7686
Epoch 62/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4634 - accuracy: 0.7696
Epoch 63/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4633 - accuracy: 0.7720
Epoch 64/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4604 - accuracy: 0.7757
Epoch 65/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4607 - accuracy: 0.7742
Epoch 66/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4606 - accuracy: 0.7726
Epoch 67/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4610 - accuracy: 0.7714
Epoch 68/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4602 - accuracy: 0.7720
Epoch 69/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4597 - accuracy: 0.7705
Epoch 70/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4605 - accuracy: 0.7708
Epoch 71/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4585 - accuracy: 0.7766
Epoch 72/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4598 - accuracy: 0.7717
Epoch 73/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4582 - accuracy: 0.7714
Epoch 74/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4578 - accuracy: 0.7714
Epoch 75/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4589 - accuracy: 0.7711
Epoch 76/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4586 - accuracy: 0.7742
Epoch 77/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4581 - accuracy: 0.7739
Epoch 78/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4570 - accuracy: 0.7742
Epoch 79/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4571 - accuracy: 0.7705
Epoch 80/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4586 - accuracy: 0.7729
Epoch 81/100

102/102 [==============================] - 0s 1ms/step - loss: 0.4577 - accuracy: 0.7739
Epoch 82/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4575 - accuracy: 0.7748
Epoch 83/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4576 - accuracy: 0.7699
Epoch 84/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4556 - accuracy: 0.7748
Epoch 85/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4550 - accuracy: 0.7732
Epoch 86/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4554 - accuracy: 0.7736
Epoch 87/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4543 - accuracy: 0.7760
Epoch 88/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4564 - accuracy: 0.7751
Epoch 89/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4559 - accuracy: 0.7677
Epoch 90/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4571 - accuracy: 0.7732
Epoch 91/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4549 - accuracy: 0.7760
Epoch 92/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4543 - accuracy: 0.7748
Epoch 93/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4541 - accuracy: 0.7763
Epoch 94/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4550 - accuracy: 0.7791
Epoch 95/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4532 - accuracy: 0.7720
Epoch 96/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4559 - accuracy: 0.7736
Epoch 97/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4547 - accuracy: 0.7736
Epoch 98/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4535 - accuracy: 0.7769
Epoch 99/100
102/102 [==============================] - 0s 2ms/step - loss: 0.4526 - accuracy: 0.7791
Epoch 100/100
102/102 [==============================] - 0s 1ms/step - loss: 0.4546 - accuracy: 0.7754
26/26 [==============================] - 0s 1ms/step - loss: 0.4797 - accuracy: 0.7607
[0.47974157333374023, 0.7607361674308777]
26/26 [==============================] - 0s 957us/step
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.74      0.76       408
           1       0.75      0.78      0.76       407

    accuracy                           0.76       815
   macro avg       0.76      0.76      0.76       815
weighted avg       0.76      0.76      0.76       815

As we see, there is considerable Improvement in the f1, recall and precision scores of Class 1 Value.
The f1 score has improved from 0.58 to 0.77.

### Oversampling

In [26]:
# Oversample 1-class and concat the DataFrames of both classes
df_class_1_over = df_class_1.sample(count_class_0, replace=True)
df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

print('Random over-sampling:')
print(df_test_over.Exitedb.value_counts())

Random over-sampling:

AttributeError: 'DataFrame' object has no attribute 'Exitedb'

In [ ]:
from sklearn.model_selection import train_test_split
X = df_test_over.drop('Exited', axis='columns')
y = df_test_over['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [ ]:
y_preds = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

f1-score for minority class 1 improved from 0.58 to 0.79.

Method3: SMOTE

To install imbalanced-learn library use pip install imbalanced-learn command

In [ ]:
X = df1.drop('Exited', axis='columns')
y = df1['Exited']

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy='minority')
X_sm, y_sm = smote.fit_resample(X, y)

y_sm.value_counts()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.2, random_state=15, stratify=y_sm)

In [ ]:
y_preds = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

### Ensemble 
### ====================================================

In [ ]:
df1.Exited.value_counts()

In [ ]:
X = df1.drop('Exited', axis='columns')
y = df1['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=15, stratify=y)

In [ ]:
df2 = X_train.copy()
df2['Exited'] = y_train

In [ ]:
df2.head()

In [ ]:
df2_class0 = df2[df2.Exited == 0]
df2_class1 = df2[df2.Exited == 1]

In [ ]:
def get_train_batch(df_majority, df_minority, start, end):
    df_train = pd.concat([df_majority[start:end], df_minority], axis=0)

    X_train = df_train.drop('Exited', axis='columns')
    y_train = df_train.Exited
    return X_train, y_train

In [ ]:
X_train, y_train = get_train_batch(df2_class0, df2_class1, 0, 1495)

y_pred1 = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

In [ ]:
X_train, y_train = get_train_batch(df2_class0, df2_class1, 1495, 2990)

y_pred2 = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

In [ ]:
X_train, y_train = get_train_batch(df2_class0, df2_class1, 2990, 4130)

y_pred3 = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy')

In [ ]:
y_pred_final = y_pred1.copy()
for i in range(len(y_pred1)):
    n_ones = y_pred1[i] + y_pred2[i] + y_pred3[i]
    if n_ones > 1:
        y_pred_final[i] = 1
    else:
        y_pred_final[i] = 0

In [ ]:
cl_rep = classification_report(y_test, y_pred_final)
print(cl_rep)

f1-score for minority class 1 is 0.57